# Generated by Django 2.2.18 on 2023-06-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230601_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ifLogged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='signature',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
