# Generated by Django 3.2.12 on 2023-07-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcardrequest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDCardRequest',
        ),
    ]
