# Generated by Django 3.2.12 on 2023-07-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('0', 'Not Paid'), ('1', 'Paid')], default='0', max_length=1),
        ),
    ]
