# Generated by Django 3.2.12 on 2023-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsAPI', '0002_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
