# Generated by Django 3.2.12 on 2023-06-29 05:19

from django.db import migrations, models
import qrgenerator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('qr_image', models.ImageField(upload_to=qrgenerator.models.qr_image_upload_to)),
                ('public_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
