# Generated by Django 3.2.12 on 2023-07-02 15:46

from django.db import migrations, models
import django.db.models.deletion
import qrgenerator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountsAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(upload_to=qrgenerator.models.qr_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsAPI.student')),
            ],
        ),
    ]
